/* Generated by `pnpm gen:api`. Do not edit by hand. */
/* Source: ../backend/openapi.json */
export interface paths {
    "/api/v1/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Land back from the forge
         * @description The attempt's `next` was made safe by forge when the sign-in started,
         *     and the attempt comes back signed, so it is used as it is.
         */
        get: operations["completeLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start a sign-in through the forge */
        get: operations["startLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End this session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where to create a forge account, when sign-up is open */
        get: operations["getRegisterUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/forge/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * An event the forge pushes for an org
         * @description The signature is the hex HMAC-SHA256 of the raw body under the org's
         *     secret, in the first of forge's signature headers the request carries,
         *     `X-Forgejo-Signature` and then `X-Gitea-Signature`.
         */
        post: operations["receiveForgeEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user and their roles */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /** Delete the account at the forge */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate the account at the forge */
        post: operations["deactivateMe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where this user is signed in */
        get: operations["listMySessions"];
        put?: never;
        post?: never;
        /** Sign out everywhere, including here */
        delete: operations["revokeAllMySessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** End one session */
        delete: operations["revokeMySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for an org to be made
         * @description The caller becomes the org's first admin once it is ready.
         */
        post: operations["createOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the org's description and display name */
        patch: operations["updateOrg"];
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The org's contests
         * @description The contests the forge lets the caller read, by name.
         */
        get: operations["listContests"];
        put?: never;
        /** Ask for a contest to be made in the org */
        post: operations["createContest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One file at a version */
        get: operations["readContestFile"];
        /** Write one file */
        put: operations["writeContestFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/files/{path}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write a file back as it was at an older version */
        post: operations["rollBackContestFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every change, newest first */
        get: operations["listContestHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/provisioning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How far making the contest has got
         * @description Not found when nothing has asked for the contest.
         */
        get: operations["getContestProvisioning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who holds a role at the contest
         * @description Everyone holding a role here, each once with the highest role they
         *     hold, highest first, including those who hold it at a broader scope.
         */
        get: operations["listContestRoles"];
        put?: never;
        /**
         * Give someone a role at the contest
         * @description A different role than the one they hold here moves them to it,
         *     which is how a person is promoted or demoted.
         */
        post: operations["grantContestRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/roles/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Take away someone's role at the contest
         * @description Every role they hold directly here goes; a role they hold at a
         *     broader scope stays.
         */
        delete: operations["revokeContestRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The contest's tasks
         * @description The tasks the forge lets the caller read, by name.
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Ask for a task to be made in the contest
         * @description Not found when the contest is not there.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where the task's files stand
         * @description The head, the latest publication, and when the head is a draft, the
         *     errors that keep it from publishing, worked out again on every read.
         */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One file at a version */
        get: operations["readTaskFile"];
        /** Write one file */
        put: operations["writeTaskFile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/files/{path}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write a file back as it was at an older version */
        post: operations["rollBackTaskFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every change, newest first */
        get: operations["listTaskHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/provisioning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How far making the task has got
         * @description Not found when nothing has asked for the task.
         */
        get: operations["getTaskProvisioning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/publications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The task's publications, oldest first */
        get: operations["listTaskPublications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether the caller sees the task and may submit to it now */
        get: operations["getTaskRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who holds a role at the task
         * @description Everyone holding a role here, each once with the highest role they
         *     hold, highest first, including those who hold it at a broader scope.
         */
        get: operations["listTaskRoles"];
        put?: never;
        /**
         * Give someone a role at the task
         * @description A different role than the one they hold here moves them to it,
         *     which is how a person is promoted or demoted.
         */
        post: operations["grantTaskRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/roles/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Take away someone's role at the task
         * @description Every role they hold directly here goes; a role they hold at a
         *     broader scope stays.
         */
        delete: operations["revokeTaskRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save the task's files, publishing them when they are valid
         * @description A valid save publishes and one that is not is kept as a draft with its
         *     errors. While the contest runs, a save that changes how the task grades
         *     is refused as `confirmation_required` unless it is confirmed or kept as a
         *     draft.
         */
        post: operations["saveTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tasks/{task}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A folder's entries */
        get: operations["listTaskTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/contests/{contest}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A folder's entries */
        get: operations["listContestTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/provisioning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How far making the org has got
         * @description Not found when nothing was asked for under that name, or someone else
         *     asked for it.
         */
        get: operations["getOrgProvisioning"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who holds a role at the org
         * @description Everyone holding a role here, each once with the highest role they
         *     hold, highest first, including those who hold it at a broader scope.
         */
        get: operations["listOrgRoles"];
        put?: never;
        /**
         * Give someone a role at the org
         * @description A different role than the one they hold here moves them to it,
         *     which is how a person is promoted or demoted.
         */
        post: operations["grantOrgRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orgs/{org}/roles/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Take away someone's role at the org
         * @description Every role they hold directly here goes; a role they hold at a
         *     broader scope stays.
         */
        delete: operations["revokeOrgRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server time in UTC */
        get: operations["getServerTime"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the process up */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the database reachable */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Change
         * @description One entry of the history: the version it made, who made it, what they
         *     said about it and when.
         */
        Change: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Author Id */
            author_id: number | null;
            /** Message */
            message: string;
            /** Version */
            version: string;
        };
        /** Contest */
        Contest: {
            /** Name */
            name: string;
        };
        /**
         * CreateContest
         * @description A contest to make, titled `title` or, without one, its name.
         */
        CreateContest: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
        };
        /** CreateOrg */
        CreateOrg: {
            /**
             * Description
             * @default
             */
            description: string;
            /** Name */
            name: string;
        };
        /**
         * CreateTask
         * @description A task to make, titled `title` or, without one, its name.
         */
        CreateTask: {
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
        };
        /**
         * DefinitionError
         * @description One thing wrong with a definition file: its YAML path, "" for the file
         *     as a whole, and a sentence a form shows beside that field.
         */
        DefinitionError: {
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        /**
         * DraftSave
         * @description A save kept as a draft: the version its files were written as, the
         *     errors that kept it from publishing, and what it held back.
         */
        DraftSave: {
            /** Errors */
            errors: components["schemas"]["DefinitionError"][];
            /** Held Back */
            held_back: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "draft";
            /** Version */
            version: string;
        };
        /**
         * FileChange
         * @description One file of a save, with the token it was read with, or null for a
         *     file the save creates.
         */
        FileChange: {
            /** Content */
            content: string;
            /**
             * Encoding
             * @default utf-8
             * @enum {string}
             */
            encoding: "utf-8" | "base64";
            /** Path */
            path: string;
            /** Token */
            token: string | null;
        };
        /**
         * FileContent
         * @description One file at one version, with the token a write presents back.
         */
        FileContent: {
            /** Content */
            content: string;
            /**
             * Encoding
             * @enum {string}
             */
            encoding: "utf-8" | "base64";
            /** Path */
            path: string;
            /** Token */
            token: string;
        };
        /**
         * GrantRequest
         * @description Give the named user `role` at the scope, moving them from any other
         *     role they hold directly there.
         */
        GrantRequest: {
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "manager" | "observer";
            /** Username */
            username: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * Holder
         * @description Someone holding `role` at the scope asked about. `scope` is where
         *     they hold it directly, and `inherited` is set when that is a broader
         *     scope, such as an org admin listed at one of the org's contests.
         */
        Holder: {
            /** Avatar Url */
            avatar_url: string | null;
            /** Inherited */
            inherited: boolean;
            /** Name */
            name: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "admin" | "manager" | "observer";
            scope: components["schemas"]["Scope"];
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /**
         * Me
         * @description The signed-in user and their roles at every scope. `degraded` is set
         *     when the forge did not answer and the identity comes from the session.
         */
        Me: {
            /** Avatar Url */
            avatar_url: string | null;
            /** Degraded */
            degraded: boolean;
            /** Email */
            email: string | null;
            /** Name */
            name: string | null;
            /** Roles */
            roles: components["schemas"]["Role"][];
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
        };
        /**
         * NotReady
         * @description Deliberately not a problem document: an orchestrator reads the status in
         *     a fixed place. What failed underneath is in the log and not here.
         */
        NotReady: {
            /**
             * Status
             * @constant
             */
            status: "not_ready";
        };
        /**
         * Problem
         * @description Extra members are allowed: `sole_admin` carries `scopes`, for instance.
         */
        Problem: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * Provisioning
         * @description How far making something has got. `steps` are the steps of its kind
         *     in the order they run, and `last_step` is the last one that completed.
         *     A failed record names the step it stopped at in `failed_step`, which is
         *     none when the work failed outside any step, and says when it is tried
         *     again, from where it stopped, in `retry_at`; both are none unless the
         *     status is `failed`. `error` is the reason the last try failed, and
         *     `attempts` counts the tries.
         */
        Provisioning: {
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            /** Failed Step */
            failed_step: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "org" | "contest" | "task";
            /** Last Step */
            last_step: string | null;
            /** Ready At */
            ready_at: string | null;
            /** Retry At */
            retry_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "ready" | "failed";
            /** Steps */
            steps: string[];
            /** Target */
            target: string;
        };
        /**
         * Publication
         * @description One publication: its number among the task's publications, the version
         *     it froze, whether it changed how the task grades and what, and when.
         */
        Publication: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Changes */
            changes: string[];
            /** Grading Changed */
            grading_changed: boolean;
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Version */
            version: string;
        };
        /**
         * PublishedSave
         * @description A save that published. `registration` says where the task's
         *     registration for grading stands: `done` by this save, `pending` with the
         *     poller, or `not_needed` because an earlier publication did it.
         */
        PublishedSave: {
            /** Changes */
            changes: string[];
            /** Grading Changed */
            grading_changed: boolean;
            /** Number */
            number: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            outcome: "published";
            /** Publication */
            publication: string;
            /**
             * Registration
             * @enum {string}
             */
            registration: "done" | "pending" | "not_needed";
        };
        /** Ready */
        Ready: {
            /**
             * Status
             * @constant
             */
            status: "ready";
        };
        /** RegisterUrl */
        RegisterUrl: {
            /** Url */
            url: string | null;
        };
        /** Role */
        Role: {
            /** Role */
            role: string;
            scope: components["schemas"]["Scope"];
        };
        /**
         * RollbackFile
         * @description Write the file as it was at `version` back as a new change, `token`
         *     being the one of the file as it is now.
         */
        RollbackFile: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /**
             * Keep As Draft
             * @default false
             */
            keep_as_draft: boolean;
            /** Message */
            message?: string | null;
            /** Token */
            token: string | null;
            /** Version */
            version: string;
        };
        /**
         * SaveRequest
         * @description The files a save writes, several at once. While the task's contest
         *     runs, `confirm` publishes a change to how the task grades, and
         *     `keep_as_draft` writes it as a draft that says what it held back; an
         *     empty save with `confirm` publishes a draft kept that way.
         */
        SaveRequest: {
            /**
             * Changes
             * @default []
             */
            changes: components["schemas"]["FileChange"][];
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /**
             * Keep As Draft
             * @default false
             */
            keep_as_draft: boolean;
            /** Message */
            message?: string | null;
        };
        /** Scope */
        Scope: {
            /** Contest */
            contest: string | null;
            /** Kind */
            kind: string;
            /** Org */
            org: string;
            /** Task */
            task: string | null;
        };
        /** ServerTime */
        ServerTime: {
            /**
             * Now
             * Format: date-time
             */
            now: string;
        };
        /**
         * SessionInfo
         * @description One place this user is signed in, described by its device and its
         *     times. The address a session came from is kept for the record and stays
         *     out of the answer.
         */
        SessionInfo: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current */
            current: boolean;
            /** Id */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** User Agent */
            user_agent: string | null;
        };
        /** Task */
        Task: {
            /** Name */
            name: string;
        };
        /**
         * TaskRelease
         * @description Whether the caller sees the task and may submit to it now, by the
         *     server's clock: `released` once the contest is published and started,
         *     the task's `release_at` has passed and it is not hidden; `visible` from
         *     then until the contest is archived; `open` while visible, before the
         *     contest's end plus the caller's own extension, with submissions not
         *     closed. `closed` is the first reason it is not open.
         */
        TaskRelease: {
            /** Closed */
            closed: ("not_released" | "archived" | "ended" | "submissions_closed") | null;
            /** Open */
            open: boolean;
            /** Released */
            released: boolean;
            /** Visible */
            visible: boolean;
        };
        /**
         * TaskState
         * @description Where a task's files stand: the version at their head, the latest
         *     publication or none, and whether the head is a draft, a state no
         *     publication froze. A draft carries the errors that keep it from
         *     publishing; a draft with none was held back, or has not been saved since
         *     it was made.
         */
        TaskState: {
            /** Draft */
            draft: boolean;
            /** Errors */
            errors: components["schemas"]["DefinitionError"][];
            /** Head */
            head: string;
            latest: components["schemas"]["Publication"] | null;
        };
        /**
         * TreeEntry
         * @description A file or a folder directly under the folder asked about.
         */
        TreeEntry: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "file" | "directory";
            /** Path */
            path: string;
            /** Size */
            size: number | null;
        };
        /**
         * UpdateOrg
         * @description The org's description, and its display name when given.
         */
        UpdateOrg: {
            /** Description */
            description: string;
            /** Display Name */
            display_name?: string | null;
        };
        /**
         * WriteFile
         * @description One file written, `token` being the one it was read with or null for
         *     a new file. For a task this is a save, and `confirm` and
         *     `keep_as_draft` do what they do for one.
         */
        WriteFile: {
            /**
             * Confirm
             * @default false
             */
            confirm: boolean;
            /** Content */
            content: string;
            /**
             * Encoding
             * @default utf-8
             * @enum {string}
             */
            encoding: "utf-8" | "base64";
            /**
             * Keep As Draft
             * @default false
             */
            keep_as_draft: boolean;
            /** Message */
            message?: string | null;
            /** Token */
            token: string | null;
        };
        /**
         * Written
         * @description A contest's file written: the version the change made.
         */
        Written: {
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    completeLogin: {
        parameters: {
            query?: {
                code?: string;
                error?: string | null;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    startLogin: {
        parameters: {
            query?: {
                /** @description A path on this site to land on */
                next?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getRegisterUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterUrl"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    receiveForgeEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deactivateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeAllMySessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeMySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrg"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    updateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrg"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listContests: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createContest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readContestFile: {
        parameters: {
            query?: {
                /** @description A version; the latest when absent */
                at?: string | null;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    writeContestFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Written"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rollBackContestFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Written"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listContestHistory: {
        parameters: {
            query?: {
                /** @description One file; every file when absent */
                path?: string | null;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getContestProvisioning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listContestRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holder"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    grantContestRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeContestRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTask"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskState"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readTaskFile: {
        parameters: {
            query?: {
                /** @description A version; the latest when absent */
                at?: string | null;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    writeTaskFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSave"] | components["schemas"]["DraftSave"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rollBackTaskFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                path: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackFile"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSave"] | components["schemas"]["DraftSave"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTaskHistory: {
        parameters: {
            query?: {
                /** @description One file; every file when absent */
                path?: string | null;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getTaskProvisioning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTaskPublications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Publication"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getTaskRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskRelease"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTaskRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holder"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    grantTaskRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeTaskRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    saveTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedSave"] | components["schemas"]["DraftSave"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listTaskTree: {
        parameters: {
            query?: {
                /** @description The folder; the top when empty */
                path?: string;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeEntry"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listContestTree: {
        parameters: {
            query?: {
                /** @description The folder; the top when empty */
                path?: string;
            };
            header?: never;
            path: {
                contest: string;
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeEntry"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOrgProvisioning: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provisioning"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listOrgRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Holder"][];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    grantOrgRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    revokeOrgRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                org: string;
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getServerTime: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerTime"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ready"];
                };
            };
            /** @description The database did not answer */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotReady"];
                };
            };
            /** @description An error, as an RFC 9457 problem document. `code` names it. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
