/**
 * Regenerates src/api/schema.d.ts from the backend's OpenAPI document.
 *
 *   pnpm gen:api                                  the ref in ./api-version
 *   pnpm gen:api --from ../backend/openapi.json   a sibling checkout
 *   pnpm gen:api --from http://localhost:8080/openapi.json   a running stack
 *
 * The pin keeps the frontend building against a known backend, so bumping
 * ./api-version is a deliberate change.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { argv, exit } from 'node:process';
import openapiTS, { astToString } from 'openapi-typescript';

const OUTPUT = resolve(import.meta.dirname, '../src/api/schema.d.ts');
const API_VERSION_FILE = resolve(import.meta.dirname, '../api-version');

function parseFromFlag(args: string[]): string | undefined {
  const index = args.indexOf('--from');
  if (index === -1) return undefined;
  const value = args[index + 1];
  if (!value) {
    console.error('--from needs a path or URL');
    exit(2);
  }
  return value;
}

async function readSource(from: string): Promise<{ label: string; document: unknown }> {
  if (from.startsWith('http://') || from.startsWith('https://')) {
    const response = await fetch(from);
    if (!response.ok) {
      throw new Error(`${from} returned ${response.status}`);
    }
    return { label: from, document: await response.json() };
  }
  const path = resolve(process.cwd(), from);
  return { label: from, document: JSON.parse(await readFile(path, 'utf8')) };
}

async function main() {
  const explicit = parseFromFlag(argv.slice(2));
  const ref = (await readFile(API_VERSION_FILE, 'utf8')).trim();
  const from =
    explicit ??
    `https://raw.githubusercontent.com/uniconhq/backend/${ref}/openapi.json`;

  const { label, document } = await readSource(from);
  const ast = await openapiTS(document as Parameters<typeof openapiTS>[0], {
    alphabetize: true,
  });
  const header = [
    '/* Generated by `pnpm gen:api`. Do not edit by hand. */',
    `/* Source: ${label} */`,
    '',
  ].join('\n');

  await writeFile(OUTPUT, header + astToString(ast), 'utf8');
  console.log(`wrote ${OUTPUT} from ${label}`);
}

await main();
